id: IE9695C47
legacy_id: P006920
ocr_import_info:
  bdrc_scan_id: W8LS19813
  source: bdrc
  ocr_info:
    timestamp: '2020-03-28T16:36:50'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-04T04:35:21.279944+00:00'
last_modified: 2022-09-04 12:35:39.330502
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W8LS19813
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW8LS19813
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: བླང་བྱའི་ཚུལ་ཁྲིམས་གཞི་བཅུ་བདུན་གྱི་རྣམ་པར་བཤད་པ་རྩ་བའི་ས་བོན།
statistics:
  ocr_word_mean_confidence_index: 0.6986067484406985
  ocr_word_median_confidence_index: 0.7599999904632568
quality: null
bases:
  I8LS19815:
    source_metadata:
      id: http://purl.bdrc.io/resource/I8LS19815
      total_pages: 704
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I8LS19815.txt
    statistics:
      ocr_word_median_confidence_index: 0.7599999904632568
      ocr_word_mean_confidence_index: 0.6986067484406985
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
