id: IE9695C47
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-28T16:41:11+00:00'
last_modified: '2022-06-08T12:28:10.990011+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W8LS19813
  title: བླང་བྱའི་ཚུལ་ཁྲིམས་གཞི་བཅུ་བདུན་གྱི་རྣམ་པར་བཤད་པ་རྩ་བའི་ས་བོན།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    F44E:
      image_group_id: I8LS19815
      title: ''
      total_pages: 704
      order: 1
      base_file: F44E.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
